<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="index, follow, all" />
        <title>Devise\Support\DeviseValidationException | Devise</title>
                    <link rel="stylesheet" type="text/css" href="../../stylesheet.css">
                            </head>
        <body id="class">
            <div class="header">
        <ul>
            <li><a href="../../classes.html">Classes</a></li>
                            <li><a href="../../namespaces.html">Namespaces</a></li>
                        <li><a href="../../interfaces.html">Interfaces</a></li>
            <li><a href="../../traits.html">Traits</a></li>
            <li><a href="../../doc-index.html">Index</a></li>
            
        </ul>

        <div id="title">Devise</div>

            <div class="type">Class</div>
    <h1><a href="../../Devise/Support.html">Devise\Support</a>\DeviseValidationException</h1>
    </div>
        <div class="content">
                <p>    class
    <strong>DeviseValidationException</strong>        extends <a href="../../Devise/Support/DeviseException.html"><abbr title="Devise\Support\DeviseException">DeviseException</abbr></a></p>

            <div class="description">
            <p>This validation exception is thrown when ever there are validation errors somewhere.</p>
            <p>It is used in the Manager class
to assert fields are valid.</p>
        </div>
    
    
    
            <h2>Methods</h2>

            <table>
                    <tr>
                <td class="type">
                    static&nbsp;<a href="../../Devise/Support/DeviseException.html"><abbr title="Devise\Support\DeviseException">DeviseException</abbr></a>
                </td>
                <td class="last">
                    <a href="#method_getFacadeRoot">getFacadeRoot</a>()
                    <p>Pretends to be a Facade for Exception</p>
                </td>
                <td><small>from&nbsp;<a href="../../Devise/Support/DeviseException.html#method_getFacadeRoot"><abbr title="Devise\Support\DeviseException">DeviseException</abbr></a></small></td>
            </tr>
                    <tr>
                <td class="type">
                    
                </td>
                <td class="last">
                    <a href="#method___construct">__construct</a>(string $message, <abbr title="Illuminate\Support\MessageBag">MessageBag</abbr> $errors)
                    <p>Construct a new Validation exception</p>
                </td>
                <td></td>
            </tr>
                    <tr>
                <td class="type">
                    <abbr title="Illuminate\Support\MessageBag">MessageBag</abbr>
                </td>
                <td class="last">
                    <a href="#method_getErrors">getErrors</a>()
                    <p>Access the errors message bag</p>
                </td>
                <td></td>
            </tr>
            </table>


        <h2>Details</h2>

                        <h3 id="method_getFacadeRoot">
        <div class="location">in <a href="../../Devise/Support/DeviseException.html#method_getFacadeRoot"><abbr title="Devise\Support\DeviseException">DeviseException</abbr></a> at line 18</div>
        <code>        static    public            <a href="../../Devise/Support/DeviseException.html"><abbr title="Devise\Support\DeviseException">DeviseException</abbr></a>
    <strong>getFacadeRoot</strong>()</code>
    </h3>
    <div class="details">
        <p>Pretends to be a Facade for Exception</p>
        <p>
</p>
        <div class="tags">
            
                            <h4>Return Value</h4>

                    <table>
        <tr>
            <td><a href="../../Devise/Support/DeviseException.html"><abbr title="Devise\Support\DeviseException">DeviseException</abbr></a></td>
            <td>
</td>
        </tr>
    </table>

            
            
                    </div>
    </div>

                <h3 id="method___construct">
        <div class="location">at line 24</div>
        <code>            public            
    <strong>__construct</strong>(string $message, <abbr title="Illuminate\Support\MessageBag">MessageBag</abbr> $errors)</code>
    </h3>
    <div class="details">
        <p>Construct a new Validation exception</p>
        <p>
</p>
        <div class="tags">
                            <h4>Parameters</h4>

                    <table>
                    <tr>
                <td>string</td>
                <td>$message</td>
                <td>
</td>
            </tr>
                    <tr>
                <td><abbr title="Illuminate\Support\MessageBag">MessageBag</abbr></td>
                <td>$errors</td>
                <td>
</td>
            </tr>
            </table>

            
            
            
                    </div>
    </div>

                <h3 id="method_getErrors">
        <div class="location">at line 35</div>
        <code>            public            <abbr title="Illuminate\Support\MessageBag">MessageBag</abbr>
    <strong>getErrors</strong>()</code>
    </h3>
    <div class="details">
        <p>Access the errors message bag</p>
        <p>
</p>
        <div class="tags">
            
                            <h4>Return Value</h4>

                    <table>
        <tr>
            <td><abbr title="Illuminate\Support\MessageBag">MessageBag</abbr></td>
            <td>
</td>
        </tr>
    </table>

            
            
                    </div>
    </div>

    
            </div>
            <div id="footer">
        Generated by <a href="http://sami.sensiolabs.org/" target="_top">Sami, the API Documentation Generator</a>.
    </div>
    </body>
</html>
